#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <stogs_rf_bridge_icons.h>

int32_t stogs_rf_bridge_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm stogs_rf_bridge!");

    return 0;
}
